//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GD_WorldEditor.rc
//
#define ID_DEFAULTS                     3
#define ID_DEFAULT                      3
#define IDC_BROWSE                      3
#define IDD_ABOUTBOX                    100
#define CG_ID_VIEW_DIALOGBAR            103
#define ID_TOOLBAR_COMBOBOX             104
#define IDC_ARROWENTITY                 104
#define ID_INDICATOR_SLOCK              106
#define ID_INDICATOR_SELINFO            107
#define ID_INDICATOR_WORLDPOS           108
#define ID_INDICATOR_CURSORINFO         109
#define ID_INDICATOR_GRID               110
#define ID_INDICATOR_SNAP               111
#define IDR_MAINFRAME                   128
#define IDR_THREDTYPE                   129
#define IDR_FUSIONTYPE                  129
#define IDR_BRUSHTOOLS                  130
#define IDS_LOAD_WARNING                130
#define IDS_NEWGROUP                    131
#define IDD_BRUSHDIALOG                 132
#define IDS_CREATEGROUPFAILED           132
#define IDD_CREATEBOX                   133
#define IDS_DEFAULTGROUPNAME            133
#define IDB_HOLLOWBOX                   134
#define IDS_NOBLANKMODEL                134
#define IDB_SOLIDBOX                    135
#define IDS_MODELEXISTS                 135
#define IDD_CREATE_SPHEROID             136
#define IDS_CAMERAENTITYNAME            136
#define IDB_SOLIDSPHERE                 137
#define IDS_MAPERROR                    137
#define IDB_HOLLOWSPHERE                138
#define IDD_CREATE_CYL                  139
#define IDB_CYLINDERBIT                 140
#define IDD_GRIDSETTINGSDIALOG          141
#define IDD_BSPMANAGERDIALOG            142
#define IDD_ENTITIES                    143
#define IDD_SELECTCLASSNAME             144
#define IDD_GROUPDIALOG                 145
#define IDD_STAIRCASEDIALOG             146
#define IDR_THRED_PALETTE1              147
#define IDD_GLOBALSETTINGS              148
#define IDD_FACEDIALOG                  149
#define IDD_TABDIALOG                   153
#define IDD_BRUSH_ENTITY_DIALOG         158
#define IDI_CUBE_PRIMITIVE              160
#define IDI_SPHEROID_PRIMITIVE          163
#define IDI_CYLINDER_PRIMITIVE          164
#define IDI_STAIRCASE_PRIMITIVE         165
#define IDI_LIGHT_ENTITY                167
#define IDI_PLAYERSTART_ENTITY          168
#define IDI_ACTOR_ENTITY                175
#define IDI_FLIPVERTICAL                176
#define IDI_FLIPHORIZONTAL              177
#define IDD_CREATE_ARCH                 178
#define IDI_ARCH_PRIMITIVE              179
#define IDD_PROGRESSDIALOG              180
#define IDD_CREATE_CONE                 181
#define IDI_CONE_PRIMITIVE              182
#define IDD_COMPILEDIALOG               183
#define IDC_PANCURSOR                   190
#define IDC_ARROWBRUSH                  191
#define IDC_POINTER                     191
#define IDD_CONSOLE                     191
#define IDD_OBJ_NAME_DLG                192
#define IDI_LIBOBJECT                   192
#define IDD_DIALOG1                     193
#define IDD_PROPEDIT                    194
#define IDD_KEYEDIT                     199
#define IDD_POINTKEYEDIT                204
#define IDD_STRUCTEDIT                  205
#define IDD_MODELEDIT                   206
#define IDD_MODELKEY                    207
#define IDI_PLAY                        208
#define IDI_RRSTART                     209
#define IDI_RRFRAME                     210
#define IDI_STOP                        211
#define IDI_FFFRAME                     212
#define IDI_FFEND                       213
#define IDD_ENTITYVISIBILITY            214
#define IDR_GROUPBAR                    219
#define ID_BRUSH_GROUPS_ADDTOGROUP      220
#define IDD_GROUPBAR                    221
#define IDD_PREFERENCES                 224
#define IDD_SKYDIALOG                   225
#define IDD_EVENTEDIT                   226
#define IDD_PATHSDIALOG                 227
#define IDD_PROJECTOPTIONS              228
#define IDC_EYEDROPPER                  229
#define IDD_LEVELOPTIONS                231
#define IDD_BOOLEDIT                    232
#define IDD_DIALOG2                     233
#define IDI_ICON1                       238
#define IDB_CREATECONE                  239
#define IDB_CREATEARCH                  240
#define IDB_CREATESTAIRS                241
#define IDI_OMNI_LIGHT_ENTITY           243
#define IDI_SPOT_LIGHT_ENTITY           244
#define IDI_SUN_LIGHT_ENTITY            245
#define IDD_MOVEDIALOG                  248
#define IDD_ROTATEDIALOG                249
#define IDD_SCALEDIALOG                 251
#define IDB_GENESIS3D                   252
#define IDD_EXPORT3DSDIALOG             254
#define IDD_SCENEDATA                   255
#define IDD_EQ_FRONTPANEL               256
#define IDD_TEXTUREPACKER               257
#define IDD_DLGRIGHTPANE                258
#define IDD_                            258
#define IDD_SB_TABSTEXTURES             258
#define IDD_MESSAGE                     259
#define IDD_SB_TABSDIALOG               260
#define IDD_SB_BRUSH_PROPERTIES         261
#define IDD_SB_MOVECAMERA               262
#define IDD_SB_TOPTABS                  263
#define IDD_SB_TB_PROPERTIES            264
#define IDD_SB_TESTDIALOG               265
#define IDD_SB_LEFTTOP                  266
#define IDD_VIEW_BOTTOMLEFT             267
#define IDD_SB_OGREVIEWER               268
#define IDD_SB_EQUITYME                 268
#define IDR_MENUSB                      274
#define IDD_SB_EXPORTOPTIONS            275
#define IDD_DIALOG3                     276
#define IDD_SB_YESNO                    276
#define IDD_SB_TB_BUTTONS               278
#define IDB_GRIDOFF                     280
#define IDB_GRIDON                      282
#define IDB_MESHON                      283
#define IDB_MESHOFF                     284
#define IDB_MESHPOINTSON                285
#define IDB_MESHPOINTSOFF               286
#define IDB_BONDINGBOXON                287
#define IDB_BONDINGBOXOFF               288
#define IDB_BONESON                     289
#define IDB_BONESOFF                    290
#define IDB_HAIRON                      291
#define IDB_HAIROFF                     292
#define IDB_TEXTURESON                  293
#define IDB_TEXTURESOFF                 294
#define IDB_NORMALSON                   295
#define IDB_NORMALSOFF                  296
#define IDB_LIGHTON                     297
#define IDB_LIGHTOFF                    298
#define IDB_TB_MODELDATA                299
#define IDB_TB_MODELDATAON              300
#define IDD_SB_BRUSHDIMENSIONS          308
#define IDD_SB_RECENTPRJ                310
#define IDD_TOPTABS_EQUITY              313
#define IDD_TB_EQ_TEST                  315
#define IDB_DUMMY                       317
#define IDD_MOUSESENSITIVITY            319
#define IDD_EQ_DROPGEN                  321
#define IDD_SB_PREFERENCES              323
#define IDD_SB_VIEWER3D                 326
#define IDB_BITMAP1                     329
#define IDB_BMPXYZ                      329
#define IDB_FULLSCREEN                  330
#define IDD_SB_VIEWMANAGER              331
#define IDD_SB_LIST                     334
#define IDD_SB_PROPERTIES               336
#define IDB_FILECHANGED                 338
#define IDB_FILECHANGEDSELECTED         339
#define IDB_FILEINACTIVE                340
#define IDB_TREE                        341
#define IDB_FILE                        342
#define IDB_FILESELECTED                343
#define IDB_BITMAP2                     344
#define IDB_FVFOLDERRED                 344
#define IDC_RESET_ALL                   1000
#define IDC_EDIT1                       1001
#define IDC_EDIT10                      1002
#define IDC_EDIT11                      1003
#define IDC_EDIT12                      1004
#define IDC_BOUNCELIMIT                 1006
#define IDC_FACELIGHTINTENSITY          1006
#define IDC_LIGHTSCALE                  1007
#define IDC_PATCHSIZE                   1008
#define IDC_REFLECTSCALE                1009
#define IDC_MINLIGHT                    1010
#define IDC_RESET_POSITION              1011
#define IDC_RESET_ROTATION              1012
#define IDC_RESET_SCALE                 1013
#define IDC_SOLID                       1014
#define IDC_XShear                      1014
#define IDC_HOLLOW                      1015
#define IDC_YSHEAR                      1015
#define IDC_XSIZE                       1016
#define IDC_ZSHEAR                      1016
#define IDC_RING                        1016
#define IDC_YSIZE                       1017
#define IDC_RESET_SHEAR                 1017
#define IDC_ZSIZE                       1018
#define IDC_THICKNESS                   1019
#define IDC_PICTURE                     1020
#define IDC_VERTSTRIPES                 1021
#define IDC_YSIZE2                      1021
#define IDC_HORSTRIPES                  1022
#define IDC_XSIZE2                      1022
#define IDC_RINGLENGTH                  1022
#define IDC_XSIZEBOT                    1023
#define IDC_ZSIZEBOT                    1024
#define IDC_TOPXSIZE                    1025
#define IDC_TOPXOFF                     1026
#define IDC_TOPZOFF                     1027
#define IDC_BOTXSIZE                    1028
#define IDC_BOTZSIZE                    1029
#define IDC_BOTXOFF                     1030
#define IDC_BOTZOFF                     1031
#define IDC_TOPZSIZE                    1032
#define IDC_GRIDSIZE                    1033
#define IDC_RebuildQuick                1035
#define IDC_REBUILDOPTIMAL              1036
#define IDC_ORIGINAL_POLYS              1037
#define IDC_SPLITS                      1038
#define IDC_TOTAL_POLYS                 1039
#define IDC_NODES                       1040
#define IDC_COPLANAR_NODES              1041
#define IDC_Defaults                    1043
#define IDC_PROGRESS1                   1046
#define IDC_PAIRS                       1047
#define IDC_PROPERTIESLIST              1047
#define IDC_SHOWLIGHTS                  1052
#define IDC_NEWKEYVALUE                 1054
#define IDC_KEY_EDIT                    1055
#define IDC_VALUE_EDIT                  1056
#define IDC_ENTITYLIST                  1057
#define IDC_ASSOCIATE_SELECTEDBRUSH     1058
#define IDC_ASSOCIATEGROUP              1059
#define IDC_NEWENTITY                   1060
#define IDC_NEWLIGHT                    1061
#define IDC_DELETEKEYVALUE              1062
#define IDC_DELETEENTITY                1063
#define IDC_LIST1                       1064
#define IDC_COLOURBUTTON                1065
#define IDC_CHECK1                      1066
#define IDC_BRUSHLIST                   1067
#define IDC_SKYRIGHT                    1067
#define IDC_VISDETAIL                   1067
#define IDC_NAME                        1068
#define IDC_CHECK3                      1068
#define IDC_SKYTOP                      1068
#define IDC_SIZELOCK                    1068
#define IDC_HULLSIZE                    1069
#define IDC_CHECK4                      1069
#define IDC_SKYBOTTOM                   1069
#define IDC_SKYFRONT                    1070
#define IDC_XSIZETOP                    1071
#define IDC_SKYBACK                     1071
#define IDC_ZSIZETOP                    1072
#define IDC_HEIGHT                      1073
#define IDC_WIDTH                       1074
#define IDC_LENGTH                      1075
#define IDC_NUMSLITS                    1075
#define IDC_NUMBEROFSTAIRS              1076
#define IDC_RADIUS                      1076
#define IDC_BUILDWATER                  1077
#define IDC_WALLSIZE                    1077
#define IDC_SIZE16                      1078
#define IDC_SIZE32                      1079
#define IDC_SIZE64                      1080
#define IDC_SIZE8                       1081
#define IDC_SHOWCOARSE                  1082
#define IDC_USEROTSNAP                  1083
#define IDC_SNAP15                      1084
#define IDC_SNAP30                      1085
#define IDC_SNAP45                      1086
#define IDC_SNAP60                      1087
#define IDC_SHOWFINE                    1088
#define IDC_SNAP90                      1088
#define IDC_ROTSNAPDEGREES              1089
#define IDC_BROWSEPAL                   1090
#define IDC_SIZE4                       1090
#define IDC_BROWSEWAD                   1091
#define IDC_PALETTEPATH                 1092
#define IDC_WADPATH                     1093
#define IDC_DISASSOCIATE                1094
#define IDC_AVENGERPATH                 1094
#define IDC_BROWSEAVENGER               1095
#define IDC_SBXOFFSET_UNIT              1097
#define IDC_SBYOFFSET_UNIT              1098
#define IDC_SBXSCALE_UNIT               1099
#define IDC_SBYSCALE_UNIT               1100
#define IDC_SBANGLE_UNIT                1101
#define IDC_SBXOFFSET_INCR              1111
#define IDC_CBSKYBACK                   1111
#define IDC_SBYOFFSET_INCR              1112
#define IDC_CBSKYLEFT                   1112
#define IDC_SBXSCALE_INCR               1113
#define IDC_SBYSCALE_INCR               1114
#define IDC_SBANGLE_INCR                1115
#define IDC_APPLY                       1118
#define IDC_RESTORE                     1119
#define IDC_COLOR                       1119
#define IDC_CANCEL                      1120
#define IDC_GROUP1                      1128
#define IDC_TEXTURELIST                 1132
#define IDD_TEXTUREDIALOG               1132
#define IDC_TEXTUREIMAGE                1133
#define IDD_LEVELOPTIONS_GD             1133
#define IDC_APPLYTEXTURE                1134
#define IDD_SB_TABSGROUPS               1134
#define IDD_SB_TABSBRUSHES              1134
#define IDD_SB_TABSTEMPLATES            1135
#define IDD_SB_TB_FILES                 1136
#define IDD_SB_MOVEBRUSH                1137
#define IDD_SB_TB_FILES2                1137
#define IDC_CUBE_PRIMITIVE              1138
#define IDD_SB_FACE_PROPERTIES          1138
#define IDC_SPHEROID_PRIMITIVE          1139
#define IDD_VIEW_BOTTOMRIGHT            1139
#define IDC_CYLINDER_PRIMITIVE          1140
#define IDD_VIEW_TOPLEFT                1140
#define IDC_STAIRCASE_PRIMITIVE         1141
#define IDD_VIEW_TOPRIGHT               1141
#define IDC_LIGHT_ENTITY                1142
#define IDC_BUILDALWAYS                 1142
#define IDC_ENTITIES                    1142
#define IDD_SB_TB_TEST                  1142
#define IDC_PLAYERSTART_ENTITY          1143
#define IDC_FLIPVERTICAL                1143
#define IDD_TB_EQ_CAMERA                1143
#define IDC_ACTOR_ENTITY                1144
#define IDC_FLIPHORIZONTAL              1144
#define IDD_SB_TB_FACES                 1144
#define IDC_ARCH_PRIMITIVE              1145
#define IDD_SB_TB_CAMERA                1145
#define IDC_CONE_PRIMITIVE              1146
#define IDD_SB_TB_TEST1                 1146
#define IDD_SB_TB_EQUITY                1146
#define IDD_SB_YESNOCANCEL              1147
#define IDC_STARTANGLE                  1148
#define IDC_ENDANGLE                    1149
#define IDC_STATUSPROGRESS1             1149
#define IDC_STATUSPROGRESS2             1150
#define IDC_RADIUS2                     1150
#define IDC_SIDES                       1151
#define IDC_FUNNEL                      1152
#define IDC_VISNONE                     1157
#define IDC_VISLEVEL1                   1158
#define IDC_VISLEVEL2                   1159
#define IDC_VISLEVEL3                   1160
#define IDC_VISLEVEL4                   1161
#define IDC_RUNGBSP                     1162
#define IDC_RUNLIGHT                    1163
#define IDC_RunAvenger                  1164
#define IDC_VISLEVEL0                   1165
#define IDC_VIS                         1165
#define IDC_TCUT                        1166
#define IDC_CONEDIT                     1167
#define IDC_TSHEET                      1167
#define IDC_STATIC2                     1168
#define IDC_MILLIRADIO                  1170
#define IDC_BRUSHEMPTY                  1170
#define IDC_CENTIRADIO                  1171
#define IDC_METERRADIO                  1172
#define IDC_RADBOOL                     1173
#define IDC_8RADIO                      1173
#define IDC_EXSAMPBOOL                  1174
#define IDC_RADIO5                      1174
#define IDC_16RADIO                     1174
#define IDC_DEGREES60                   1174
#define IDC_FASTPBOOL                   1175
#define IDC_RADIO6                      1175
#define IDC_32RADIO                     1175
#define IDC_BRUSHHOLLOW                 1175
#define IDC_DEGREES90                   1175
#define IDC_FULLVIS                     1176
#define IDC_1RADIO                      1176
#define IDC_VISVERBOSE                  1177
#define IDC_2RADIO                      1177
#define IDC_BSPVERBOSE                  1178
#define IDC_ENTITYCOMBO                 1178
#define IDC_4RADIO                      1178
#define IDC_ENTITYVERBOSE               1179
#define IDC_USEMINLIGHT                 1180
#define IDC_TJUNCT                      1181
#define IDC_XEDIT                       1182
#define IDC_YEDIT                       1183
#define IDC_ZEDIT                       1184
#define IDC_STRUCTLIST                  1185
#define IDC_SIZETEXT                    1188
#define IDC_MODELLIST                   1189
#define IDC_BRUSHLOCK                   1190
#define IDC_DESELECTBRUSHES             1191
#define IDC_SELECTBRUSHES               1192
#define IDC_SELECTBRUSHES2              1193
#define IDC_SELECTBRUSHES3              1194
#define IDC_ADDTOCURRENT                1194
#define IDC_SELECTBRUSHES4              1195
#define IDC_REMOVEFROMCURRENT           1195
#define IDC_VISIBLE                     1196
#define IDC_SUPPRESSHIDDEN              1197
#define IDC_SELECTBRUSHES5              1197
#define IDC_CREATENEWGROUP              1197
#define IDC_REMOVEGROUP                 1198
#define IDC_DESELECT                    1199
#define IDC_ADDKEY                      1200
#define IDC_ANIMATE                     1200
#define IDC_ADDEVENT                    1201
#define IDC_DELETEKEY                   1202
#define IDC_SELECT                      1203
#define IDC_DELETEEVENT                 1204
#define IDC_DELETEMODEL                 1205
#define IDC_MODELCOMBO                  1206
#define IDC_KEYSLIST                    1207
#define IDC_ADDMODEL                    1208
#define IDC_ADDBRUSHES                  1209
#define IDC_REMOVEBRUSHES               1210
#define IDC_EDITMODEL                   1211
#define IDC_EDITKEY                     1212
#define IDC_EDITEVENT                   1213
#define IDC_TEXELRADIO                  1214
#define IDC_METRICRADIO                 1215
#define IDC_GROUPCOMBO                  1216
#define IDC_METRICGRID                  1217
#define IDC_LOCKED                      1218
#define IDC_TEXELGRID                   1219
#define IDC_SPINROTSNAPDEGREES          1220
#define IDC_BRUSHSOLID                  1221
#define IDC_SETMODELORIGIN              1222
#define IDC_BRUSHWINDOW                 1223
#define IDC_CLONEMODEL                  1224
#define IDC_BRUSHWAVY                   1225
#define IDC_LOCKORIGIN                  1226
#define IDC_BRUSHFLOCKING               1226
#define IDC_BRUSHCLIP                   1227
#define IDC_BRUSHHINT                   1228
#define IDC_FACEMIRROR                  1229
#define IDC_BRUSHSHEET                  1229
#define IDC_BRUSHAREA                   1230
#define IDC_FACEFULLBRIGHT              1231
#define IDC_PREFSGRIDBG                 1232
#define IDC_FACEGOURAUD                 1232
#define IDC_FACESKY                     1233
#define IDC_PREFSGRIDMAJOR              1234
#define IDC_PREFSGRID                   1234
#define IDC_FACEFLAT                    1234
#define IDC_BRUSHSUBTRACT               1235
#define IDC_SKYLEFT                     1236
#define IDC_FACELIGHT                   1237
#define IDC_PREFSGRIDMINOR              1238
#define IDC_PREFSSNAPGRID               1238
#define IDC_CBSKYRIGHT                  1239
#define IDC_PATHPREFS                   1239
#define IDC_BRUSHTRANSLUCENT            1240
#define IDC_CBSKYTOP                    1241
#define IDC_CBSKYBOTTOM                 1242
#define IDC_CBSKYFRONT                  1243
#define IDC_BRUSHDETAIL                 1244
#define IDC_EVENTTIME                   1245
#define IDC_EVENTSTRING                 1246
#define IDC_ENTITIESONLY                1247
#define IDC_EDITXOFFSET                 1248
#define IDC_EDITYOFFSET                 1249
#define IDC_EDITXSCALE                  1250
#define IDC_EDITYSCALE                  1251
#define IDC_EDITANGLE                   1252
#define IDC_CBXOFFSET                   1253
#define IDC_CBYOFFSET                   1254
#define IDC_CBXSCALE                    1255
#define IDC_CBYSCALE                    1256
#define IDC_CBANGLE                     1257
#define IDC_EDITXLIGHTSCALE             1258
#define IDC_EDITYLIGHTSCALE             1259
#define IDC_SBXLIGHTSCALE_UNIT          1260
#define IDC_SBYLIGHTSCALE_UNIT          1261
#define IDC_SBXLIGHTSCALE_INCR          1262
#define IDC_SBYLIGHTSCALE_INCR          1263
#define IDC_CBXLIGHTSCALE               1264
#define IDC_CBYLIGHTSCALE               1265
#define IDC_EDITTRANSLUCENCY            1266
#define IDC_LBLTRANSLUCENCYVALUE        1269
#define IDC_LBLHULLSIZE                 1270
#define IDC_EDITTXLSEARCH               1271
#define IDC_EDITPREVIEW                 1272
#define IDC_EDITHEADERS                 1273
#define IDC_EDITOBJECTSDIR              1274
#define IDC_EDITTXLIB                   1275
#define IDC_PATHS                       1276
#define IDC_COMPILEOPTIONS              1277
#define IDC_SAVE                        1278
#define IDC_LIGHTMAPSCALE               1279
#define IDC_DRAWSCALE                   1280
#define IDC_BOOLLIST                    1281
#define IDC_EDITTXL                     1281
#define IDC_CONTENTSLIST                1282
#define IDC_EDITHEADERSDIR              1282
#define IDC_MIPMAPBIAS                  1283
#define IDC_EDITPAWNINI                 1283
#define IDC_TEXTURELOCK                 1284
#define IDC_EDITACTORSDIR               1284
#define IDC_AXISX                       1285
#define IDC_REFLECTIVITY                1285
#define IDC_AXISY                       1286
#define IDC_FACETRANSLUCENCY            1286
#define IDC_AXISZ                       1287
#define IDC_EDITSPEED                   1288
#define IDC_EDITSCALE                   1289
#define IDC_TRANSPARENT                 1289
#define IDC_BROWSETXL                   1290
#define IDC_BROWSEPAWNINI               1291
#define IDC_GROUP_TEXTURE_OFFSET_SCALE  1293
#define IDC_GROUP_LIGHTMAP_SCALE        1294
#define IDC_LABEL_TEXTURE_OFFSET_SCALEX 1295
#define IDC_LABEL_TEXTURE_OFFSET_SCALEY 1296
#define IDC_LABEL_TEXTURE_OFFSET_SCALEANGLE 1297
#define IDC_LABEL_LIGHTMAP_SCALEX       1298
#define IDC_LABEL_LIGHTMAP_SCALEY       1299
#define IDC_LABEL_REFLECTIVITY          1300
#define IDC_LABEL_MIPMAPBIAS            1301
#define IDC_LABEL_NUM_FACES             1303
#define IDC_LABEL_NUM_BRUSHES           1304
#define IDC_RESETALL                    1306
#define IDC_ADDTEXTURE                  1307
#define IDC_REMOVETEXTURE               1308
#define IDC_ABSOLUTE                    1309
#define IDC_RELATIVE                    1310
#define IDC_FINALY                      1314
#define IDC_FINALZ                      1315
#define IDC_FINALX                      1316
#define IDC_XEDITBOX                    1317
#define IDC_YEDITBOX                    1318
#define IDC_ZEDITBOX                    1319
#define IDC_DIRECTION                   1320
#define IDC_LEFT                        1321
#define IDC_DEGREES                     1322
#define IDC_DEGREES45                   1323
#define IDC_DEGREES180                  1324
#define IDC_DEGREES270                  1325
#define IDC_DEGREESFREE                 1326
#define IDC_EDITFREE                    1327
#define IDC_ABOUTINFORMATION            1328
#define IDC_STATIC1                     1329
#define IDC_STATIC3                     1330
#define IDC_STATIC4                     1331
#define IDC_STATIC5                     1332
#define IDC_CCW                         1333
#define IDC_CW                          1334
#define IDC_RECTANGULAR                 1335
#define IDC_ROUND                       1336
#define IDC_MASSIVE                     1337
#define IDC_STEPS                       1338
#define IDC_EXPORTALL                   1339
#define IDC_EXPORTSELECTED              1340
#define IDC_EXPORTLIGHTS                1341
#define IDC_GROUPFILE                   1342
#define IDC_LISTGROUP                   1343
#define IDC_BTSETVIEW                   1344
#define IDC_BTWIRE                      1345
#define IDC_BTSELECTALL                 1346
#define IDC_BTDESELECTALL               1347
#define IDC_STTXTFILE                   1348
#define IDC_GEINFO                      1349
#define IDC_ADD                         1351
#define IDC_BUTTON3                     1352
#define IDC_BUTTON4                     1353
#define IDC_BTTXLDELETE                 1353
#define IDC_BT_TB_SELECTALL             1353
#define IDC_BTTBSHEAR                   1353
#define IDC_BTSHOWTEXTURES              1353
#define IDC_BT_TT_ZEROCAM               1353
#define IDC_BT_BOXROOM                  1353
#define IDC_BUTTON5                     1354
#define IDC_PREVIEW                     1355
#define IDC_TBSHOWHAIR                  1355
#define IDC_BUTTON6                     1356
#define IDC_TEXTURELIST2                1357
#define IDC_TBBOUNDBOX                  1357
#define IDC_BTTXLOPEN                   1358
#define IDC_BTSHOWLIGHT2                1358
#define IDC_BTTESTDLG                   1359
#define IDC_BUTTON7                     1359
#define IDC_STTDTXLNAME                 1360
#define IDC_LISTTDTEXTURES              1361
#define IDC_BASETEXTURE2                1362
#define IDC_BUTTON1                     1363
#define IDC_BTTDAPPLY                   1363
#define IDC_BTBUILDVIEW                 1363
#define IDC_TBTEMPLATES                 1363
#define IDC_GD_CUBE_PRIMITIVE           1363
#define IDC_BTTEST                      1363
#define IDC_BTRESETANGLES               1363
#define IDC_BT_TBF_QUICKLOAD            1363
#define IDC_BT_TB_TEXTURED              1363
#define IDC_BTTBSELECT                  1363
#define IDC_TEST                        1363
#define IDC_BT_CHANGE_NAME              1363
#define IDC_BTSHOWBONES                 1363
#define IDC_BTCLEARFILES                1363
#define IDC_BT_TT_TEST                  1363
#define IDC_BT_TT_MODEL                 1363
#define IDC_BT_OGRERUNNING              1363
#define IDC_CKNORMAL                    1363
#define IDC_BT_EQ_GROUPS                1363
#define IDC_BT_EQ_UPDATE                1363
#define IDC_BT_DELETEBRUSH              1363
#define IDC_BT_TT_MOVECAMRA             1363
#define IDC_NOX                         1363
#define IDC_NONO                        1363
#define IDC_WETEST                      1363
#define IDC_BT_UPPERLEFT                1363
#define IDC_BANNER                      1364
#define IDC_GD_CYLINDER_PRIMITIVE       1364
#define IDC_BT_BROWSE                   1364
#define IDC_TBINFO2                     1364
#define IDC_CKVERYSLOW                  1364
#define IDC_BT_LOWERRIGHT               1364
#define IDC_BUTTON8                     1364
#define IDC_BTFACEPREVIOUS              1364
#define IDC_STTEXT                      1365
#define IDC_GD_SPHEROID_PRIMITIVE       1365
#define IDC_BT_FOLDER_NAME              1365
#define IDC_CKSLOW                      1365
#define IDC_BT_LOWERLEFT                1365
#define IDC_STMESSAGE                   1366
#define IDC_GD_CONE_PRIMITIVE           1366
#define IDC_STTEXT2                     1366
#define IDC_CKFAST                      1366
#define IDC_BT_UPPERRIGHT               1366
#define IDC_STTXL                       1367
#define IDC_GD_STAIRCASE_PRIMITIVE      1367
#define IDC_BTWORLDINFO                 1368
#define IDC_GD_ARCH_PRIMITIVE           1368
#define IDC_TBTEXTURES                  1369
#define IDC_TBGROUPS                    1370
#define IDC_STTOP                       1372
#define IDC_STBOTTOM                    1373
#define IDC_STGENERAL                   1374
#define IDC_STTOPX                      1375
#define IDC_STWALL                      1376
#define IDC_STZTOP                      1377
#define IDC_STBOTX                      1378
#define IDC_STBOTZ                      1379
#define IDC_STYSIZE                     1380
#define IDC_GD_BRUSHLIST                1381
#define IDC_ST_GD_GROUPS                1382
#define IDC_BRUSHCOUNT                  1383
#define IDC_ST_GD_BRUSHCOUNT            1384
#define IDC_BT_GD_BRUSHPROPERTIES       1385
#define IDC_BRUSH_PROPERTIESLIST        1386
#define IDC_EDITNAME                    1387
#define IDC_STTOPXSIZE                  1389
#define IDC_STTOPZSIZE                  1390
#define IDC_STTOPXOFFSET                1391
#define IDC_STTOPZOFFSET                1392
#define IDC_STWALLTHICKNESS             1393
#define IDC_STRINGLENGTH                1394
#define IDC_STSTRIPES                   1395
#define IDC_STBOTXSIZE                  1396
#define IDC_STBOTZSIZE                  1397
#define IDC_STBOTXOFFSET                1398
#define IDC_STBOTZOFFSET                1399
#define IDC_EDCAMX                      1400
#define IDC_STCAMX                      1401
#define IDC_EDCAMY                      1402
#define IDC_STCAMY                      1403
#define IDC_STCAMERA                    1404
#define IDC_STPOSITION                  1405
#define IDC_EDCAMZ                      1406
#define IDC_STDIAMETER                  1406
#define IDC_STROTITION                  1406
#define IDC_STROTATION                  1406
#define IDC_STCAMZ                      1407
#define IDC_STVERTSTRIPS                1407
#define IDC_STROTATION2                 1407
#define IDC_EDCAMANGLEX                 1408
#define IDC_STWALLSIZE                  1408
#define IDC_STCAMANGLEX                 1409
#define IDC_STSTYLE                     1409
#define IDC_EDCAMANGLEY                 1410
#define IDC_STRADIUS                    1410
#define IDC_STCAMANGLEY                 1411
#define IDC_STVERTICLESTIPES            1411
#define IDC_EDCAMANGLEZ                 1412
#define IDC_STHORISTIPS                 1412
#define IDC_STCAMANGLEZ                 1413
#define IDC_STHEIGHT                    1413
#define IDC_STANGLES                    1414
#define IDC_STWIDTH                     1414
#define IDC_STLENGTH                    1415
#define IDC_STSTEPS                     1416
#define IDC_STSTARTANGLE                1417
#define IDC_STENDANGLE                  1418
#define IDC_STINNERRADIUS               1419
#define IDC_STNUMSEGS                   1420
#define IDC_STSHAPE                     1421
#define IDC_STTHICKNESS                 1422
#define IDC_STSIDES                     1423
#define IDC_STNAME                      1424
#define IDC_STCAMPOS                    1425
#define IDC_CKWORLDCENTRE               1426
#define IDC_CKCAMPOSITION               1427
#define IDC_ST_GD_TEMPLATES             1428
#define IDC_ST_GD_TEXTURES              1429
#define IDC_BT_UPDATE                   1430
#define IDC_STHELP                      1431
#define IDC_BTEDITFILE                  1432
#define IDC_STTEXTURE                   1433
#define IDC_STALPHA                     1434
#define IDC_BT_TB_DESELECTALL           1450
#define IDC_BT_TB_WORLDINFO             1451
#define IDC_BT_TB_WIRED                 1452
#define IDC_BT_TB_FILE                  1453
#define IDC_BT_TB_MODIFY                1454
#define IDC_BTTBMOVEROTATE              1455
#define IDC_BT_TB_WORLDINFO2            1455
#define IDC_BT_TB_NEWVIEW               1455
#define IDC_BTSCALE                     1456
#define IDC_BTINSERT                    1458
#define IDC_BTRESETPOSITION             1459
#define IDC_STBRUSH                     1460
#define IDC_BTTDFACEPROPERTIES          1461
#define IDC_STLEFTTOP                   1463
#define IDC_STARTEQUITY                 1464
#define IDC_STATICTEST                  1465
#define IDC_BUTTON2                     1466
#define IDC_UPDATE                      1466
#define IDC_ACTOR                       1466
#define IDC_BT_DIMENSIONS               1466
#define IDC_BT_TT_CAMERA                1466
#define IDC_BT_TT_FREE                  1466
#define IDC_BT_TB_FACES                 1466
#define IDC_ST_BANNER                   1467
#define IDC_UPDATE2                     1467
#define IDC_BTTB_FULLSCREEN             1467
#define IDC_ST_FN                       1468
#define IDC_ST_NAME                     1469
#define IDC_ST_FLD                      1470
#define IDC_ST_FOLDER                   1471
#define IDC_ST_SUBFOLDER_NAME           1472
#define IDC_CK_SUBFOLDER                1473
#define IDC_TBSHOWFACES                 1474
#define IDC_TBSHOWGRID                  1475
#define IDC_BTSHOWNORMALS               1476
#define IDC_BTSHOWPOINTS                1477
#define IDC_ST_GD_SELECTED              1478
#define IDC_ST_SELECTED                 1479
#define IDC_ST_BP_SELECTEDBRUSHES       1480
#define IDC_LIST_SELECTEDBRUSHES        1481
#define IDC_BT_TB_TEST                  1482
#define IDC_BT_TB_EQUITY                1482
#define IDC_STWIDTHHEIGHT               1483
#define IDC_ED_BRUSH_POSX               1484
#define IDC_ED_BRUSH_POSY               1485
#define IDC_ED_BRUSH_POSZ               1486
#define IDC_SBPOSX                      1487
#define IDC_CBPOSXDELTA                 1488
#define IDC_STPOSX                      1489
#define IDC_CBPOSYDELTA                 1490
#define IDC_CBPOSZDELTA                 1491
#define IDC_SBPOSY                      1492
#define IDC_SBPOSZ                      1493
#define IDC_STPOSY                      1494
#define IDC_STPOSZ                      1495
#define IDC_ED_BRUSH_POSX2              1496
#define IDC_RECENTPRJLIST               1496
#define IDC_ED_BRUSH_SCALEX             1496
#define IDC_STROTX                      1497
#define IDC_BTTBDIMENSIONS              1497
#define IDC_STSIZEX                     1497
#define IDC_ED_BRUSH_POSY2              1498
#define IDC_BT_TT_RESETCAM              1498
#define IDC_ED_BRUSH_SCALEY             1498
#define IDC_STROTY                      1499
#define IDC_STSIZEY                     1499
#define IDC_ED_BRUSH_POSZ2              1500
#define IDC_ED_BRUSH_SCALEZ             1500
#define IDC_STROTZ                      1501
#define IDC_STSIZEZ                     1501
#define IDC_SBPOSX2                     1502
#define IDC_SBSCALEX                    1502
#define IDC_CBPOSXDELTA2                1503
#define IDC_CBSIZEXDELTA                1503
#define IDC_CBPOSYDELTA2                1504
#define IDC_CBSIZEYDELTA                1504
#define IDC_CBPOSZDELTA2                1505
#define IDC_CBSIZEZDELTA                1505
#define IDC_SBPOSY2                     1506
#define IDC_SBSCALEY                    1506
#define IDC_SBPOSZ2                     1507
#define IDC_SBSCALEZ                    1507
#define IDC_SBPOSXH                     1508
#define IDC_SBPOSYH                     1509
#define IDC_SBPOSZH                     1510
#define IDC_BT_CAMERASPEED              1510
#define IDC_ED_BRUSH_POSX3              1511
#define IDC_STBANNER                    1511
#define IDC_ED_BRUSH_ROTX3              1511
#define IDC_STROTX2                     1512
#define IDC_TITLE                       1512
#define IDC_ED_BRUSH_POSY3              1513
#define IDC_STSELECTED                  1513
#define IDC_ED_BRUSH_ROTY3              1513
#define IDC_STROTY2                     1514
#define IDC_LISTSELECTION               1514
#define IDC_ED_BRUSH_POSZ3              1515
#define IDC_LISTGROUPDETAIL             1515
#define IDC_ED_BRUSH_ROTZ3              1515
#define IDC_STROTZ2                     1516
#define IDC_BT_TT_ALL_BRUSH             1516
#define IDC_SBPOSX3                     1517
#define IDC_CK_JUSTEQUITY               1517
#define IDC_CBPOSXDELTA3                1518
#define IDC_CK_NEWEQUITY                1518
#define IDC_SBFORWARDBACK               1518
#define IDC_CBROTXDELTA3                1518
#define IDC_CBPOSYDELTA3                1519
#define IDC_SBLEFTRIGHT                 1519
#define IDC_CBROTYDELTA3                1519
#define IDC_CBPOSZDELTA3                1520
#define IDC_BT_TB_CAMERA                1520
#define IDC_CBROTZDELTA3                1520
#define IDC_SBPOSY3                     1521
#define IDC_BT_TT_ZEROCAMRA             1521
#define IDC_SBPOSZ3                     1522
#define IDC_BT_TB_TEST2                 1522
#define IDC_FIRST_MODEX                 1523
#define IDC_STTXLFILE                   1524
#define IDC_SBROTXH                     1525
#define IDC_SBROTYH                     1526
#define IDC_BT_RESTORE                  1526
#define IDC_SCROLLBAR3                  1527
#define IDC_SBROTZH                     1527
#define IDC_BT_PREVIEW                  1527
#define IDC_BT_SELECTED                 1528
#define IDC_ADDTOSCENE                  1528
#define IDC_FACELIST                    1529
#define IDC_LISTFACEPROPERTIES          1530
#define IDC_BT_ETEST                    1531
#define IDC_BT_BOXSOLID                 1532
#define IDC_BT_BOXHOLLOW                1533
#define IDC_BT_BOXCUTBRUSH              1534
#define IDC_BOXDEFAULTS                 1535
#define IDC_BTFACENEXT                  1536
#define IDC_TREE1                       1537
#define IDC_BT_VIEWUPDATE               1538
#define ID_BRUSH_PRIMITIVES_CUBE        32771
#define ID_BRUSH_PRIMITIVES_PYRAMID     32772
#define ID_BRUSH_PRIMITIVES_SPHEROID    32773
#define ID_BRUSH_PRIMITIVES_CONE        32774
#define ID_BRUSH_PRIMITIVES_CYLINDER    32775
#define ID_BRUSH_SUBTRACTFROMWORLD      32776
#define ID_TOOLS_CAMERA                 32777
#define ID_AXIS_X                       32781
#define ID_AXIS_Y                       32782
#define ID_AXIS_Z                       32783
#define ID_TOOLS_BRUSH_MOVEROTATEBRUSH  32784
#define ID_TOOLS_BRUSH_SCALEBRUSH       32785
#define ID_TOOLS_BRUSH_RESETBRUSH       32786
#define ID_TOOLS_BRUSH_ATTRIBUTES       32791
#define ID_TOOLS_BRUSH_SHOWBRUSH        32792
#define ID_FILE_EXPORT                  32799
#define ID_TOOLS_USEGRID                32801
#define ID_TOOLS_GRIDSETTINGS           32802
#define ID_VIEW_3DWIREFRAME             32806
#define ID_VIEW_SOLIDRENDER             32807
#define ID_VIEW_TOPVIEW                 32808
#define ID_VIEW_SIDEVIEW                32809
#define ID_VIEW_FRONTVIEW               32810
#define ID_VIEW_TEXTUREVIEW             32811
#define ID_VIEW_4VIEWS                  32812
#define ID_TOOLS_BSPMANAGER             32813
#define ID_TOOLS_BRUSH_SHEARBRUSH       32814
#define ID_ENTITIES_PLACELIGHT          32817
#define ID_ENTITIES_EDITOR              32819
#define ID_TOOLS_ENTITY                 32823
#define ID_ENTITIES_SHOW                32824
#define ID_GROUPS_MAKENEWGROUP          32833
#define ID_BRUSH_GROUPEDITOR            32834
#define ID_VIEW_SHOW_ALLGROUPS          32836
#define ID_VIEW_SHOW_VISIBLEGROUPS      32837
#define ID_VIEW_SHOW_CURRENTGROUP       32838
#define ID_TOOLS_BRUSH_ADJUSTMENTMODE   32849
#define ID_BRUSH_SELECTED_DELETE        32850
#define ID_BRUSH_SELECTED_COPYTOCURRENT 32853
#define ID_BRUSH_PRIMITIVES_STAIRCASE   32856
#define ID_TOOLS_BRUSH_ROTATE90         32857
#define ID_VIEW_TEXTUREBROWSER          32859
#define ID_FILE_MAPSETTINGS             32860
#define ID_GBSPNOWATER                  32861
#define ID_ENTITIES_COPYCURRENT         32862
#define ID_ENTITIES_HIDENONLIGHTS       32865
#define ID_TOOLS_BRUSH_MOVESELECTEDBRUSHES 32867
#define ID_TOOLS_GROUPMOVEMENTMODE      32870
#define ID_BRUSH_REMOVESELECTEDFROMGROUP 32871
#define ID_TOOLS_FACE_ATTRIBUTES        32876
#define ID_TOOLS_FACE_RESETFACE         32881
#define ID_TOOLS_FACE_ADJUSTMENTMODE    32883
#define ID_CONSTRAINHOLLOWS             32885
#define ID_GENERALSELECT                32886
#define ID_VIEW_OLDVIEW                 32890
#define ID_TOOLS_RESET_THING            32890
#define ID_THING_ATTRIBUTES             32891
#define ID_TOOLS_CARVE                  32892
#define IDC_VIEWTOOLBAR_COMBOBOX        32893
#define ID_VIEW_3DVIEWBARS              32903
#define ID_TOOLS_BRUSH_SHOWASSOCIATEDENTITY 32905
#define ID_ENTITY_CENTERINBRUSH         32906
#define ID_CENTERTHING                  32908
#define ID_COMPILE                      32909
#define ID_TOOLS_TEMPLATE               32910
#define ID_MODEL_NEW                    32913
#define ID_NEW_LIB_OBJECT               32914
#define ID_MODEL_DELETE                 32915
#define ID_MODEL_ADDSELECTEDBRUSHES     32916
#define ID_MODEL_REMOVESELECTEDBRUSHES  32917
#define ID_MODEL_SELECTBRUSHES          32918
#define ID_MODEL_DESELECTMODELBRUSHES   32919
#define ID_MODEL_SELECTMODEL            32920
#define ID_ENTITYVISIBILITY             32922
#define ID_VIEW_NEW                     32923
#define ID_BRUSHINFORMATION             32924
#define IDC_PLACE_OBJECT_BUTTON         32925
#define IDS_CANT_OPEN_FILE              32925
#define IDC_OBJECT_SELECT_COMBO         32926
#define IDC_PLACE_LIGHT                 32926
#define IDC_ENTITY_COMBO                32927
#define IDM_MODEBAR                     32928
#define IDC_OBJECT_COMBO                32928
#define IDM_TABBAR                      32929
#define IDC_PLACE_FOG_LIGHT             32929
#define IDC_PLACE_SPOT_LIGHT            32930
#define IDC_PLACE_SUN                   32931
#define IDC_PLACE_SUN_LIGHT             32931
#define IDM_GROUPBAR                    32933
#define ID_GROUPBAR_SEP                 32934
#define ID_GROUPBAR_COM                 32935
#define ID_ADDTOCURRENT                 32937
#define ID_REMOVEFROMCURRENT            32938
#define ID_DESELECTALL                  32941
#define ID_SELECTALL                    32942
#define IDM_REBUILD_BSP                 32943
#define ID_VIEWLEAKFINDER               32944
#define IDM_PREFERENCES                 32945
#define ID_VIEW_SHOW_CLIP               32947
#define ID_VIEW_SHOW_HINT               32949
#define ID_VIEW_SHOW_DETAIL             32950
#define ID_TOOLS_SCALEWORLD             32951
#define ID_TOOLS_BRUSH_MAKENEWEST       32952
#define ID_TOOLS_SETTEXTURESCALE        32953
#define ID_EDIT_DELETE                  32954
#define ID_BRUSH_PRIMITIVES_ARCH        32955
#define ID_TOOLS_NEXTBRUSH              32956
#define ID_TOOLS_PREVBRUSH              32957
#define ID_TOOLS_ADDTOLEVEL             32958
#define ID_TOOLS_TOGGLEADJUSTMODE       32959
#define ID_VIEW_ZOOMIN                  32960
#define ID_VIEW_ZOOMOUT                 32961
#define ID_FILE_IMPORT                  32962
#define ID_HELP_HOWDOI                  32965
#define IDM_LEVELOPTIONS                32966
#define IDS_CANTLOADTXL                 32967
#define IDS_ENTITY_WARNING              32968
#define IDS_CANTOPENBMP                 32969
#define IDS_INVALIDBITMAPFILE           32970
#define IDS_FAILED16555RGB              32971
#define IDS_FAILEDADDTOWAD              32972
#define IDS_REPLACEBMPINWAD             32973
#define IDS_BMPSIZEPROBLEM              32974
#define IDS_REMOVETEXTURES              32975
#define IDS_REMOVETEXTURE               32976
#define IDS_CANTREMOVETEXTURE           32977
#define IDS_CANTSAVETXL                 32978
#define ID_MODE_MOVE                    32985
#define ID_MODE_SCALE                   32986
#define ID_CAMERA_GOTO                  32995
#define ID_CAMERA_CENTERONVIEW          32996
#define ID_TEMPLATE_SPOTLIGHT           32997
#define ID_TEMPLATE_FOGLIGHT            32998
#define ID_TEMPLATE_LIBRARYOBJECT       32999
#define ID_MODIFY_MOVETOCENTEROFVIEW    33003
#define ID_MODIFY_ROTATE                33004
#define ID_EDIT_SELECT_BRUSH_ALL        33008
#define ID_EDIT_SELECT_FACES_NEXT       33012
#define ID_EDIT_SELECT_FACES_PREVIOUS   33013
#define ID_EDIT_SELECT_ENTITIES_ALL     33014
#define ID_EDIT_SELECT_ENTITIES_NEXT    33015
#define ID_EDIT_SELECT_ENTITIES_PREVIOUS 33016
#define ID_EDIT_SELECT_FACES_ALLINSELECTEDBRUSHES 33017
#define ID_VIEWPORT_CENTERONSELECTION   33018
#define ID_VIEWPORT_CENTERONCAMERA      33019
#define ID_EDIT_DESELECT_BRUSHES        33021
#define ID_EDIT_DESELECT_FACES          33022
#define ID_EDIT_DESELECT_ENTITIES       33023
#define ID_BUTTON33030                  33030
#define ID_CAMERA_CENTERONSELECTION     33032
#define ID_VIEWPORT_GOTO                33033
#define ID_CAMERA_BACK                  33034
#define ID_CAMERA_FORWARD               33035
#define ID_CAMERA_LEFT                  33036
#define ID_CAMERA_RIGHT                 33037
#define ID_CAMERA_LOOK_UP               33038
#define ID_CAMERA_LOOK_DOWN             33039
#define ID_CAMERA_UP                    33040
#define ID_CAMERA_DOWN                  33041
#define IDS_SCALEFACTORZERO             33042
#define ID_VIEWPORT_LINKVIEWPORTS       33045
#define ID_TEMPLATE_SUNLIGHT            33046
#define ID_VIEW_SHOW_ACTORS             33047
#define ID_DEBUG_TEST                   33048
#define ID_DEBUG_SETVIEW                33049
#define ID_EQUITYSB_ZEROCAMERA          33050
#define ID_FILE_EXPORTGDSB_GAMEDIRECTORG3DS 33052
#define ID_FILE_EXPORT_OLDEXPORT        33053
#define ID_EQUITYSB_TXLEDITOR           33054
#define ID_EQUITYSB_FACEPROPERTIES      33055
#define ID_FILE                         33056
#define ID_CAMERAMODE_MODEL             33057
#define ID_CAMERAMODE_FREE              33058
#define ID_CAMERAMODE_FIRST             33059
#define ID_CAMERA_RESETVIEW             33060
#define ID_FILE_WORLDEDITORPROJECT      33061
#define ID_RENDER_CROSSHAIR             33062
#define ID_RENDER_FACES                 33063
#define ID_FILE_EXPORT33064             33064
#define ID_EXPORT_OGRE3D                33065
#define ID_OGRE3D_MESH                  33066
#define ID_FILE_IMPORT33067             33067
#define ID_IMPORT_WORLDEDITORPROJECT    33068
#define ID_CAMERA_ZEROVIEW              33069
#define ID_FILE_CLEARMODEL              33070
#define ID_IMPORT_WAVEFRONTOBJ          33071
#define ID_IMPORT_GENESIS3DACT          33072
#define ID_DEBUG_ACTORTOWORLD           33073
#define ID_FILE_IMPORT33074             33074
#define ID_IMPORT_GENESIS3DACTOR        33075
#define ID_WINDOW_QUICKCOMMAND          33076
#define ID_WINDOW_COMMANDPANEL          33077
#define ID_FILE_CLOSE33078              33078
#define ID_EXPORT_WAVEFRONTOBJ          33079
#define ID_FILE_RECENT                  33080
#define ID_DEBUG_SHOWCAMERAPOSITIONS    33081
#define ID_DEBUG_BOUNDINGBOX            33082
#define ID_DEBUG_GENERAL                33083
#define ID_EQUITYSB_PREFERENCESWE       33084
#define ID_DEBUG_PREFERENCESWE          33085
#define ID_PHYSICS_PHYSICS              33086
#define ID_PHYSICS_DEBUGDRAW            33087
#define ID_FILE_SAVE33088               33088
#define ID_FILE_SAVESB                  33089
#define ID_RENDER_BRUSEHS               33090
#define IDS_HELPINFORMATION             38000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        345
#define _APS_NEXT_COMMAND_VALUE         33091
#define _APS_NEXT_CONTROL_VALUE         1539
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
